[package]
name = "rw-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "5.1.4", features = ["u128", "bit"] }
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.1"
ctrlc = "3.4.4"
rand = "0.8.5"
